// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5pCcildgPPCEFeFB29SaMolz7-IgPQ00',
    appId: '1:747865893957:web:950cb25daf172d1326472c',
    messagingSenderId: '747865893957',
    projectId: 'coba-a9002',
    authDomain: 'coba-a9002.firebaseapp.com',
    storageBucket: 'coba-a9002.appspot.com',
    measurementId: 'G-EW5KBG49XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQDJBz8os-ZwS-eTBXkdQOPIRU4Ojaec',
    appId: '1:747865893957:android:eca52942a48e6bc726472c',
    messagingSenderId: '747865893957',
    projectId: 'coba-a9002',
    storageBucket: 'coba-a9002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJRpg8Pg2cXezynrLiWbxIF-j1a76H8-I',
    appId: '1:747865893957:ios:e441849cf805c92226472c',
    messagingSenderId: '747865893957',
    projectId: 'coba-a9002',
    storageBucket: 'coba-a9002.appspot.com',
    iosClientId: '747865893957-2hi814n5l4ts1ugdts79tq80k557ovr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJRpg8Pg2cXezynrLiWbxIF-j1a76H8-I',
    appId: '1:747865893957:ios:e441849cf805c92226472c',
    messagingSenderId: '747865893957',
    projectId: 'coba-a9002',
    storageBucket: 'coba-a9002.appspot.com',
    iosClientId: '747865893957-2hi814n5l4ts1ugdts79tq80k557ovr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskmanager',
  );
}
